version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_net

  backend:
    build:
      context: ./backend
    container_name: agenda_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/meu_banco
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend
    container_name: agenda_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app_net
      
    environment:
      - NODE_ENV=production

networks:
  app_net:
    driver: bridge
