version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    # IMPORTANTE: Usa o bind mount local. Lembre-se de deletar 'postgres_data'
    # em caso de falha de esquema: Remove-Item -Recurse -Force ./postgres_data
    volumes:
      - /var/lib/postgresql/data
    networks:
      - app_net

  backend:
    # Garante que as mudanças locais (ex: ddl-auto=create) sejam usadas
    build:
      context: ./backend
    container_name: agenda_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/meu_banco
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha
       # Força o Hibernate a criar o schema do zero no CI
      SPRING_JPA_HIBERNATE_DDL_AUTO: "create"
      
    ports:
      - "3000:3000"
    depends_on:
      - db
    # CORREÇÃO: Espera a porta 5432 abrir
    # Requer que o 'nc' (netcat) esteja instalado no seu Dockerfile do backend.
    # Se 'nc' não estiver disponível, substitua por 'sleep 15' temporariamente.
    # Espera o Postgres estabilizar antes de iniciar o Spring Boot
    command: >
      /bin/sh -c "
        echo 'Aguardando DB por 10 segundos...';
        sleep 10;
        echo 'DB pronto. Iniciando backend.';
        java -jar /app/app.jar
      "
    networks:
      - app_net

  frontend:
    # Garante o build local para o frontend
    build:
      context: ./frontend
    container_name: agenda_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
