name: CI/CD

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch: # permite rodar manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # necessário para enviar ao GHCR
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------- FRONTEND ----------
      - name: Build imagem FRONTEND
        run: |
          docker build \
            -t ghcr.io/${GITHUB_REPOSITORY,,}/frontend:${{ github.sha }} \
            -f ./frontend/Dockerfile ./frontend
          docker tag ghcr.io/${GITHUB_REPOSITORY,,}/frontend:${{ github.sha }} ghcr.io/${GITHUB_REPOSITORY,,}/frontend:latest

      - name: Push imagem FRONTEND
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY,,}/frontend:${{ github.sha }}
          docker push ghcr.io/${GITHUB_REPOSITORY,,}/frontend:latest

      # ---------- BACKEND ----------
      - name: Build imagem BACKEND
        run: |
          docker build \
            -t ghcr.io/${GITHUB_REPOSITORY,,}/backend:${{ github.sha }} \
            -f ./backend/Dockerfile ./backend
          docker tag ghcr.io/${GITHUB_REPOSITORY,,}/backend:${{ github.sha }} ghcr.io/${GITHUB_REPOSITORY,,}/backend:latest

      - name: Push imagem BACKEND
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY,,}/backend:${{ github.sha }}
          docker push ghcr.io/${GITHUB_REPOSITORY,,}/backend:latest
