name: CI/CD

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch: # permite rodar manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # necessário para enviar ao GHCR
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------- FRONTEND ----------
      - name: Build imagem FRONTEND
        run: |
          IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/frontend
          docker build -t $IMAGE_NAME:${{ github.sha }} ./frontend
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push imagem FRONTEND
        run: |
          IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/frontend
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      # ---------- BACKEND ----------
      - name: Build imagem BACKEND
        run: |
          IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/backend
          docker build -t $IMAGE_NAME:${{ github.sha }} ./backend
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push imagem BACKEND
        run: |
          IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/backend
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
